# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Matt Do Amaral"
theme = "hugo-agency-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-142402614-2"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Mathias Do Amaral"
  description = "Bienvenido a mi espacio"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "La Pagina no puede ser encontrada"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Matt Do Amaral"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Ocupación"
    portfolio = "Proyectos"
    about = "Conóceme"
    team = "Mentores"
    contact = "Contacto"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    # url = "http://gohugo.io"
    # name = "Hugo"
    # weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
     # weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "que gusto tenerte aqui!"
    subtitle = "Bienvenido!"
    buttonText = "Conocer mas"


  # Services section
  [params.services]
    enable = true
    title = "Ocupación"
    subtitle = "Genero valor de manera asertiva en distintos tipos de relaciones, a través de conocimiento y actitud brindo soluciones y experiencias trabajando y aprendiendo de personas muy talentosas"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-users"
      title = "Desarrollo Personal"
      description = "Diariamente desarrollo nuevas y mejores características para ser la mejor versión de mí mismo con el propósito de agregarle valor a las personas."
      #url = "#"

    [[params.services.row.list]]
      icon = "fa-credit-card"
      title = "Educación Financiera"
      description = "Constantemente trabajo en el manejo de mis finanzas personales que me ayudan a un mejor control sobre mis ingresos y gastos. Buscando adquirir más activos y deshacerme de pasivos, para lograr así la libertad financiera."
      #url = "#"

    [[params.services.row.list]]
      icon = "fa-camera"
      title = "Fotografía"
      description = "Una de mis pasiones, me ayuda a expandir mi mente y a tener nuevos puntos de vista, no sólo al momento de estar con mi cámara, sino en mi día a día y al tratar con diferentes personas."
      #url = "#"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Proyectos"
    subtitle = "Desde 2015 decidí que quería tomar un camino diferente al que la sociedad me trataba de imponer, desde ese año realicé varios proyectos y planifique varios más a largo plazo, acá te cuento algunos y como extra te comparto mi forma de pensar sobre ciertos temas."

    [params.portfolio.modal]
      client = "Cliente"
      date = "Fecha"
      category = "Categoría"
      buttonText = "Cerrar proyecto"


    # About section
  [params.about]
    enable = true
    title = "Conóceme"
    subtitle = "Hola, soy Mathias Do Amaral Argote, emprendedor, trader, apasionado de la fotografía, una de mis actividades favoritas es conocer personas y educarme constantemente en las áreas de Educación financiera, desarrollo personal y emocional."
    endpoint = "se parte<br>de mi<br>historia!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "2016"
      title = "No seré uno más...."
      description = "Empiezo mi curiosidad por Ir más allá, me llama la atención hacer música y subirla a youtube, descubro que me gusta aprender y compartir ese aprendizaje con los demás."

    [[params.about.events]]
      img = "2.jpg"
      date = "2017"
      title = "Mi Primer acercamiento"
      description = "Este año con pocos conocimientos de fotografía entré a una de las mejores empresas de fotografia del país, DxT Magazine, en este punto de mi vida sólo descubrí que me gustaba relacionarme con las personas, hacer amigos nuevos y pasarla bien, aún estaba en colegio pero ya tenía una vida bastante complicada"

    [[params.about.events]]
      img = "3.jpg"
      date = "2018"
      title = "Tomo el control de mi vida"
      description = "Ya estaba trabajando en mí mismo y mejorando mis relaciones interpersonales, experimenté una red de mercadeo, conocí a muchas personas increíbles y exitosas y decidí que quería ser Empresario."

    [[params.about.events]]
      img = "4.jpg"
      date = "2019"
      title = "Empieza el juego en serio"
      description = "Despierta mi pasión por leer pues creo que es la mejor manera de aprender de las mejores personas, fortalezco mi relación con mis mentores, decido cambiar mis hábitos y descubro que mi propósito de vida es Inspirar a Un millón de personas y ser un ejemplo de ser humano, me enfoco en trabajar más en mí y a descubrir Cómo mejorar la vida de las personas a mi alrededor, cambio radicalmente de forma positiva a mi círculo más cercano pues yo soy el resultado de éste."


  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "¡Conoce a mis Mentores!"
    subtitle = "Un equipo increible!"
    description = "Una relación entre un mentor y un discípulo puede durar años o puede darse durante una cita en una cafetería. Cuando eres el mentor de alguien durante un largo tiempo, en verdad llegas a conocer y entender su personalidad, estilo de aprendizaje y objetivos, lo cual puede hacer que le ofrezcas consejos más relevantes conforme pase el tiempo."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "1.jpg"
      name = "Jaime Toledo"
      position = "Abogado - Emprendedor"
    # reportsTo = "CTO"
      livesIn = "La Paz, Bolivia"
    #  scope = [
    #    "UX for [member dashboard](#)",
    #    "Maintainer for [awesome-project](#)",
    #    "Open Source [community management](#)"
    #  ]
      # For bio markdown and even multiline strings are available.
      bio = """Kay is an awesome Lead Designer with heaps of experience in the field of UX.
She worked at Pied Piper for years until they went belly up."""
      social = [
      #  ["fa-twitter", "#"],
        ["fa-facebook", "https://www.facebook.com/Jimmy.toledo.bolivia/"],
        ["fa-instagram", "https://www.instagram.com/jimmy.toledo_/"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Alejandro Leyton"
      position = "Productor - Empresario"
      livesIn = "La Paz, Bolivia"
      social = [
       # ["fa-linkedin", "https://www.linkedin.com/in/alejandro-leyton-204071179/"],
        ["fa-facebook", "https://www.facebook.com/alejandro.leytonn/"],
        ["fa-instagram", "https://www.instagram.com/alejandro.leyton_/"]
      ]

    [[params.team.members]]
      img = "3.jpg"
      name = "Maya Portillo"
      position = "Fotógrafa - Empresaria"
      livesIn = "La Paz, Bolivia"
      social = [
      #  ["fa-twitter", "#"],
        ["fa-facebook", "https://www.facebook.com/foto.maya.portillo/"],
        ["fa-instagram", "https://www.instagram.com/maya.portillo/"]
      ]

  # Client section
    [params.clients_list]
      enable = true
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"

      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"

  # Contact section
  [params.contact]
    enable = false
    title = "Contácto"
    subtitle  = "Para una pronta respuesta, sería genial si me escribes a mi correo: info.matt.doamaral@gmail.com"
    buttonText = "Enviar Mensaje"
    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "info.matt.doamaral@gmail.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    [params.contact.captcha]
       sitekey = "6Lcb4qoUAAAAALfAmHO6CY3TWvd5mE3Ux2sLrWkh"

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Tu Nombre *"
      warning = "Por favor ingresa tu nombre."

    [params.contact.form.email]
      text = "Tu Email *"
      warning = "Por favor ingresa tu dirección de correo."

    [params.contact.form.phone]
      text = "Tu Teléfono *"
      warning = "Por favor ingresa tu número de teléfono."

    [params.contact.form.message]
      text = "Tu Mensaje *"
      warning = "Por favor ingresa un mensaje."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Publicado bajo licencia GNU/GPL"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "#"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "#"
      title = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
